[package]
edition = "2021"
name = "rate-limit-example"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.55.3"
aws-sdk-dynamodb = "0.28.0"
tokio = {version = "1.29.1", features = ["full"]}
